In [ ]:
print("hello")

hello


In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Features: Age, Height, BP
X = np.array([
    [20, 165, 110],
    [25, 170, 120],
    [30, 175, 125],
    [35, 180, 130],
    [40, 185, 140]
])

# Target: Weight
y = np.array([55, 62, 70, 78, 85])

# Create model
model = LinearRegression()

# Train model
model.fit(X, y)

# Predict weight for:
# Age = 28, Height = 172 cm, BP = 122
prediction = model.predict([[28, 172, 122]])

print("Predicted Weight:", prediction[0])

Predicted Weight: 66.10000000000002


In [ ]:
from sklearn.linear_model import LinearRegression

# Age, Height
X = [[20, 165], [25, 170], [30, 175], [35, 180]]

# BP
y = [110, 120, 125, 130]

model = LinearRegression()
model.fit(X, y)

bp = model.predict([[28, 172]])

print("Predicted BP:", bp[0])

Predicted BP: 121.25


In [ ]:
import pandas as pd
data = pd.read_csv('bp.csv')

In [ ]:
import pandas as pd
data = pd.read_csv('bp.csv')
data.head()
y = data['Systolic BP (mm Hg)']
x = data.drop(['Systolic BP (mm Hg)','Subject_ID'], axis=1)
print(x.shape, y.shape)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

(16, 2) (16,)


In [2]:
import pandas as pd
data = pd.read_csv("bp.csv")
data.head()

,Subject_ID,Age (years),Weight (kg),Systolic BP (mm Hg)
0,1,60,58,117
1,2,61,90,120
2,3,74,96,145
3,4,57,72,129
4,5,63,62,132


In [3]:
y = data['Systolic BP (mm Hg)']
x = data.drop(['Systolic BP (mm Hg)','Subject_ID'], axis=1)
print(x.shape, y.shape)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

(16, 2) (16,)


In [4]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](2,)","[0.77,0.43]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](2,)","['Age (years)','Weight (kg)']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,44.35
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,2
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(2)


In [ ]:
age = int(input("Enter the age of the patient: "))
weight = int(input("Enter the weight of the patient: "))

bp = model.predict([[age, weight]])

print("The predicted systolic BP is:", bp[0])""

The predicted systolic BP is: 89.65360923535027


c:\Users\biren\OneDrive\Desktop\aiml intenship\aiml\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


HOUSE RENTAL PREDICTOR

In [2]:
import pandas as pd
data = pd.read_csv("hr.csv")
data.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner


In [3]:
y= data['Rent']
x= data.drop(['Rent','Posted On','City','Point of Contact'],axis=1)
print(x.shape, y.shape)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

(4746, 8) (4746,)


In [5]:
pip install category_encoders

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import category_encoders as ce
encoder=ce.LeaveOneOutEncoder()
X = encoder.fit_transform(x,y)

In [8]:
print(X)

      BHK  Size         Floor     Area Type  Area Locality  Furnishing Status  \
0       2  1100  14164.719198  18676.943967    6500.000000       22468.505513   
1       2   800  17947.602740  18672.853988    3500.000000       38727.130222   
2       2  1000  17957.876712  18674.080982   23600.000000       38728.463556   
3       2   800  14458.465608  18676.943967   22000.000000       22468.505513   
4       2   850  14465.079365  52405.438398   34993.451327       22469.883682   
...   ...   ...           ...           ...            ...                ...   
4741    2  1000  22249.168675  52402.173269   16500.000000       38729.352444   
4742    3  2000  25119.095477  18669.173006   34993.451327       38723.130222   
4743    3  1750  22008.204819  52393.466260   30000.000000       38720.463556   
4744    3  1500  34993.451327  52389.112756   43839.285714       38716.019111   
4745    2  1000  18794.117647  52402.173269   15750.000000       22465.749173   

      Tenant Preferred  Bat

In [1]:
print(x)

NameError: name 'x' is not defined

In [2]:
import pandas as pd
data= pd.read_csv('hr.csv')
data.head()

y=data['Rent']
x= data.drop(['Rent','Posted On', 'Area Type','City'], axis=1)

import category_encoders as ce
encoder = ce.LeaveOneOutEncoder(return_df= True)
X =encoder.fit_transform(x, y)

print(X)

      BHK  Size         Floor  Area Locality  Furnishing Status  \
0       2  1100  14164.719198    6500.000000       22468.505513   
1       2   800  17947.602740    3500.000000       38727.130222   
2       2  1000  17957.876712   23600.000000       38728.463556   
3       2   800  14458.465608   22000.000000       22468.505513   
4       2   850  14465.079365   34993.451327       22469.883682   
...   ...   ...           ...            ...                ...   
4741    2  1000  22249.168675   16500.000000       38729.352444   
4742    3  2000  25119.095477   34993.451327       38723.130222   
4743    3  1750  22008.204819   30000.000000       38720.463556   
4744    3  1500  34993.451327   43839.285714       38716.019111   
4745    2  1000  18794.117647   15750.000000       22465.749173   

      Tenant Preferred  Bathroom  Point of Contact  
0         31216.953238         2      16706.291757  
1         31214.048795         1      16703.181337  
2         31214.920128         1    

In [3]:
#min-max Scaling
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
x=scaler.fit_transform(X)

print(x)

import pandas as pd
x= pd.DataFrame(x,columns=X.columns)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25, random_state=42)
model= LinearRegression()
model.fit(x_train,y_train)

model.predict(x_train[1:2])

[[0.2        0.13642053 0.01174726 ... 0.01795978 0.11111111 0.00321938]
 [0.2        0.09887359 0.01736193 ... 0.01780886 0.         0.00316481]
 [0.2        0.12390488 0.01737718 ... 0.01785413 0.         0.00318118]
 ...
 [0.4        0.21777222 0.0233888  ... 0.01758247 0.22222222 0.99965557]
 [0.4        0.1864831  0.04266189 ... 0.99558704 0.11111111 0.99954076]
 [0.2        0.12390488 0.01861836 ... 0.58744851 0.11111111 0.00319209]]


array([15184.5928521])

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
model = LinearRegression()
model.fit(x_train, y_train)

prediction = model.predict(x_test)

In [16]:
new_data = pd.DataFrame({
    "BHK": [2],
    "Size": [1200],
    "Floor": [2],
    "Area Type": ["Super Area"],
    "Area Locality": ["Bandel"],
    "Furnishing Status": ["Unfurnished"],
    "Tenant Preferred": ["Family"],
    "Bathroom": [2],
    "Point of Contact": ["Contact Owner"]
})

new_data = encoder.transform(new_data)
new_data = scaler.transform(new_data)

result = model.predict(new_data)

print("Predicted Rent =", result[0])

ValueError: Unexpected input dimension 9, expected 8

In [17]:
print(X.columns.tolist())
print(new_data.columns.tolist())

['BHK', 'Size', 'Floor', 'Area Locality', 'Furnishing Status', 'Tenant Preferred', 'Bathroom', 'Point of Contact']
['BHK', 'Size', 'Floor', 'Area Type', 'Area Locality', 'Furnishing Status', 'Tenant Preferred', 'Bathroom', 'Point of Contact']


In [21]:
new_data = pd.DataFrame({
    "BHK": [2],
    "Size": [1200],
    "Floor": ["2 out of 3"],          # String
    "Area Locality": ["Bandel"],
    "Furnishing Status": ["Unfurnished"],
    "Tenant Preferred": ["Bachelors/Family"],
    "Bathroom": [2],
    "Point of Contact": ["Contact Owner"]
})

print(new_data)

new_data = encoder.transform(new_data)
print(new_data)

new_data = scaler.transform(new_data)
print(new_data)

result = model.predict(new_data)

print("Predicted Rent =", result[0])

   BHK  Size       Floor Area Locality Furnishing Status  Tenant Preferred  \
0    2  1200  2 out of 3        Bandel       Unfurnished  Bachelors/Family   

   Bathroom Point of Contact  
0         2    Contact Owner  
   BHK  Size         Floor  Area Locality  Furnishing Status  \
0    2  1200  17333.974359         8250.0       22461.635813   

   Tenant Preferred  Bathroom  Point of Contact  
0      31210.792683         2      16704.206468  
[[1.06182913e+01 1.51250137e+04 3.80731203e+05 1.62649380e+05
  6.70295204e+04 9.29803861e+04 1.91941719e+01 3.59109737e+04]]
Predicted Rent = 3961638413.4584503


In [22]:
import joblib

joblib.dump(
    {
        "encoder": encoder,
        "scaler": scaler,
        "model": model
    },
    "house_rent_prediction.pkl"
)

print("Model Saved Successfully!")

Model Saved Successfully!


In [23]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error
import category_encoders as ce
import joblib

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
import category_encoders as ce

pipeline = Pipeline([
    ("encoder", ce.LeaveOneOutEncoder()),
    ("scaler", MinMaxScaler()),
    ("model", LinearRegression())
])

In [32]:
pipeline.fit(X_train, y_train)

NameError: name 'X_train' is not defined